'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsOperaciones
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="wsOperaciones.wsCalculadoraSoap")>  _
    Public Interface wsCalculadoraSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As wsOperaciones.HelloWorldRequest) As wsOperaciones.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As wsOperaciones.HelloWorldRequest) As System.Threading.Tasks.Task(Of wsOperaciones.HelloWorldResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sumar", ReplyAction:="*")>  _
        Function Sumar(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sumar", ReplyAction:="*")>  _
        Function SumarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Restar", ReplyAction:="*")>  _
        Function Restar(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Restar", ReplyAction:="*")>  _
        Function RestarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicar", ReplyAction:="*")>  _
        Function Multiplicar(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicar", ReplyAction:="*")>  _
        Function MultiplicarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dividir", ReplyAction:="*")>  _
        Function Dividir(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dividir", ReplyAction:="*")>  _
        Function DividirAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Factorial", ReplyAction:="*")>  _
        Function Factorial(ByVal n As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Factorial", ReplyAction:="*")>  _
        Function FactorialAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/potencia", ReplyAction:="*")>  _
        Function potencia(ByVal a As Double, ByVal b As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/potencia", ReplyAction:="*")>  _
        Function potenciaAsync(ByVal a As Double, ByVal b As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function Seno(ByVal angulo As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function SenoAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function Tangente(ByVal angulo As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function TangenteAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RaizCuadrada", ReplyAction:="*")>  _
        Function RaizCuadrada(ByVal numero As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RaizCuadrada", ReplyAction:="*")>  _
        Function RaizCuadradaAsync(ByVal numero As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RaizEnesima", ReplyAction:="*")>  _
        Function RaizEnesima(ByVal numero As Double, ByVal raiz As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RaizEnesima", ReplyAction:="*")>  _
        Function RaizEnesimaAsync(ByVal numero As Double, ByVal raiz As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/numinverso", ReplyAction:="*")>  _
        Function numinverso(ByVal numero As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/numinverso", ReplyAction:="*")>  _
        Function numinversoAsync(ByVal numero As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As wsOperaciones.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsOperaciones.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As wsOperaciones.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsOperaciones.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsCalculadoraSoapChannel
        Inherits wsOperaciones.wsCalculadoraSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsCalculadoraSoapClient
        Inherits System.ServiceModel.ClientBase(Of wsOperaciones.wsCalculadoraSoap)
        Implements wsOperaciones.wsCalculadoraSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsOperaciones_wsCalculadoraSoap_HelloWorld(ByVal request As wsOperaciones.HelloWorldRequest) As wsOperaciones.HelloWorldResponse Implements wsOperaciones.wsCalculadoraSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As wsOperaciones.HelloWorldRequest = New wsOperaciones.HelloWorldRequest()
            inValue.Body = New wsOperaciones.HelloWorldRequestBody()
            Dim retVal As wsOperaciones.HelloWorldResponse = CType(Me,wsOperaciones.wsCalculadoraSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsOperaciones_wsCalculadoraSoap_HelloWorldAsync(ByVal request As wsOperaciones.HelloWorldRequest) As System.Threading.Tasks.Task(Of wsOperaciones.HelloWorldResponse) Implements wsOperaciones.wsCalculadoraSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of wsOperaciones.HelloWorldResponse)
            Dim inValue As wsOperaciones.HelloWorldRequest = New wsOperaciones.HelloWorldRequest()
            inValue.Body = New wsOperaciones.HelloWorldRequestBody()
            Return CType(Me,wsOperaciones.wsCalculadoraSoap).HelloWorldAsync(inValue)
        End Function
        
        Public Function Sumar(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.Sumar
            Return MyBase.Channel.Sumar(nro1, nro2)
        End Function
        
        Public Function SumarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.SumarAsync
            Return MyBase.Channel.SumarAsync(nro1, nro2)
        End Function
        
        Public Function Restar(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.Restar
            Return MyBase.Channel.Restar(nro1, nro2)
        End Function
        
        Public Function RestarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.RestarAsync
            Return MyBase.Channel.RestarAsync(nro1, nro2)
        End Function
        
        Public Function Multiplicar(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.Multiplicar
            Return MyBase.Channel.Multiplicar(nro1, nro2)
        End Function
        
        Public Function MultiplicarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.MultiplicarAsync
            Return MyBase.Channel.MultiplicarAsync(nro1, nro2)
        End Function
        
        Public Function Dividir(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.Dividir
            Return MyBase.Channel.Dividir(nro1, nro2)
        End Function
        
        Public Function DividirAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.DividirAsync
            Return MyBase.Channel.DividirAsync(nro1, nro2)
        End Function
        
        Public Function Factorial(ByVal n As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.Factorial
            Return MyBase.Channel.Factorial(n)
        End Function
        
        Public Function FactorialAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.FactorialAsync
            Return MyBase.Channel.FactorialAsync(n)
        End Function
        
        Public Function potencia(ByVal a As Double, ByVal b As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.potencia
            Return MyBase.Channel.potencia(a, b)
        End Function
        
        Public Function potenciaAsync(ByVal a As Double, ByVal b As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.potenciaAsync
            Return MyBase.Channel.potenciaAsync(a, b)
        End Function
        
        Public Function Seno(ByVal angulo As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.Seno
            Return MyBase.Channel.Seno(angulo)
        End Function
        
        Public Function SenoAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.SenoAsync
            Return MyBase.Channel.SenoAsync(angulo)
        End Function
        
        Public Function Tangente(ByVal angulo As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.Tangente
            Return MyBase.Channel.Tangente(angulo)
        End Function
        
        Public Function TangenteAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.TangenteAsync
            Return MyBase.Channel.TangenteAsync(angulo)
        End Function
        
        Public Function RaizCuadrada(ByVal numero As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.RaizCuadrada
            Return MyBase.Channel.RaizCuadrada(numero)
        End Function
        
        Public Function RaizCuadradaAsync(ByVal numero As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.RaizCuadradaAsync
            Return MyBase.Channel.RaizCuadradaAsync(numero)
        End Function
        
        Public Function RaizEnesima(ByVal numero As Double, ByVal raiz As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.RaizEnesima
            Return MyBase.Channel.RaizEnesima(numero, raiz)
        End Function
        
        Public Function RaizEnesimaAsync(ByVal numero As Double, ByVal raiz As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.RaizEnesimaAsync
            Return MyBase.Channel.RaizEnesimaAsync(numero, raiz)
        End Function
        
        Public Function numinverso(ByVal numero As Double) As Double Implements wsOperaciones.wsCalculadoraSoap.numinverso
            Return MyBase.Channel.numinverso(numero)
        End Function
        
        Public Function numinversoAsync(ByVal numero As Double) As System.Threading.Tasks.Task(Of Double) Implements wsOperaciones.wsCalculadoraSoap.numinversoAsync
            Return MyBase.Channel.numinversoAsync(numero)
        End Function
    End Class
End Namespace
